### ISSUE TITLE
error messages for `npm run build` do not include route which error'd

### ISSUE THREAD

**Issue by ramses0** [marko-js/marko-starter#27]
[marko-starter marko-starter-demo] Error building project. Error: Parameter "username" is required.
    at replace (/home/rames/Git/abc/play-estn/server/node_modules/reverse-path/index.js:39:19)
    at String.replace (<anonymous>)
    at reversePath (/home/rames/Git/abc/play-estn/server/node_modules/reverse-path/index.js:24:17)
    at buildRoute (/home/rames/Git/abc/play-estn/server/node_modules/marko-starter/src/util/buildAllRoutes.js:30:21)
    at Promise.all.routes.map (/home/rames/Git/abc/play-estn/server/node_modules/marko-starter/src/util/buildAllRoutes.js:16:14)
    at Array.map (<anonymous>)
    at module.exports (/home/rames/Git/abc/play-estn/server/node_modules/marko-starter/src/util/buildAllRoutes.js:14:36)
    at _runProjectTasks.then.then (/home/rames/Git/abc/play-estn/server/node_modules/marko-starter/index.js:151:24)
    at <anonymous>
npm ERR! code ELIFECYCLE

**Comment by austinkelleher** [comment]
@ramses0 thanks for the report. Is that error coming from your project? (`Error: Parameter "username" is required.`) It's not coming from marko-starter. If so, how are you throwing the error?
