### ISSUE TITLE
[BUG] Plugin: Cannot assign to read only property 'name' of function

### ISSUE THREAD

**Issue by maxmilton** [marko-js/marko-starter#32]
When using plugins with marko-starter it throws an error: `TypeError: Cannot assign to read only property 'name' of function`.

<details><summary>Click to expand full error</summary>

  ```
[marko-starter plugins] Installed plugin: lasso
(node:24324) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'name' of function 'function (lasso, config) {

    var sassHandler = {
        properties: {
            path: 'string',
         ...<omitted>...
}'
    at plugins.forEach (/home/max/Development/prowearegenkicom/auth/node_modules/marko-starter/src/plugin-manager.js:39:17)
    at Array.forEach (<anonymous>)
    at Object.exports.installPlugins (/home/max/Development/prowearegenkicom/auth/node_modules/marko-starter/src/plugin-manager.js:32:11)
    at beforeStartPromise.then (/home/max/Development/prowearegenkicom/auth/node_modules/marko-starter/index.js:75:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
(node:24324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```
</details>

To reproduce use a `project.js` like:

```javascript
```

**Comment by austinkelleher** [comment]
Hey @MaxMilton. Thanks for the report. Looks like you forgot to add your project.js. Can you please paste that? Thanks!

**Comment by maxmilton** [comment]
Sorry somehow github dupplicated and mangled my issue, see https://github.com/marko-js/marko-starter/issues/33
